teachmeanything/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('accounts/', include('users.urls')),
    path('sensei/',include('sensei.urls')),
    

]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .views import change_grasp_power_view
from .views import UserView, signup

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    path('profile/',  login_required(UserView.as_view()), name='profile'),
    path('signup/', signup, name='signup'),
    path('change_grasp_power/', change_grasp_power_view, name='change_grasp_power'),
]

templates/change_grasp_power.html
{% block content %}
  <h1>Change grasp power</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/landing_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'landing_page.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="content">
        <h2>WELCOME TO</h2>
        <h1 class="title">TeachMeAnything.AI
          <div class="aurora">
            <div class="aurora__item"></div>
            <div class="aurora__item"></div>
            <div class="aurora__item"></div>
            <div class="aurora__item"></div>
          </div>
        </h1>
        <!-- <p class="subtitle">Get Started</p> -->
        <a href="{% url 'users:profile'%}">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Get Started
        </a>
    
      </div>
</body>
</html>

templates/login.html
<h1>Login</h1>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<form method="post">
  <div class="form-outline mb-4">
  {% csrf_token %}
  {{ form.as_p }}
  
</div>
  <button type="submit">Login</button>
</form>

<a href="{% url 'users:signup'%}">
<button>Signup</button>
</a>

templates/login_test.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">

<div class="login-box">
  <h2>Login</h2>
  <form>
    <div class="user-box">
      {{form.email}}
      <label>Username</label>
    </div>

    <div class="user-box">
      {{form.password}}
      <label>Password</label>
    </div>
    <a href="#">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Submit
    </a>
  </form>
</div>

templates/profile_trial.html
<!-- semantic UI -->
<link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
<!--Chart js-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
<!-- jQuery -->


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<h1>My profile</h1>
<p>
  {{ object }}
</p>
<div>
  <script>
  $(document).ready(function(){
    const ctx = document.getElementById('myChart');

new Chart(ctx, {
  type: 'radar',
  data: {
    labels: ['grasp_power','comprehension','engagement','learning_speed','curiosity','confidence'],
    datasets: [{
      label: 'Your Learning Score',
      data: [{{user_data.grasp_power}}, {{user_data.comprehension}},{{user_data.engagement}},{{user_data.learning_speed}},{{user_data.curiosity}},{{user_data.confidence}}],
      borderWidth: 1,
      backgroundColor: 'rgba(255, 99, 132, 0.2)',
      borderColor: 'rgb(255, 99, 132)',
      pointBackgroundColor: 'rgb(255, 99, 132)',
      pointBorderColor: '#fff',
      pointHoverBackgroundColor: '#fff',
      pointHoverBorderColor: 'rgb(255, 99, 132)',
    }]
  },
  options: {
    scales: {
      y: {
        beginAtZero: true
      }
    }
  }
});
});
  </script>
<div>
  <div>
    <canvas id="myChart" width="400" height="100"></canvas>
  </div>
</div>
</div>






<div>
  <a href="{% url 'users:logout' %}">Logout</a>
</div>

templates/sensei_base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'sensei_base.css' %}">

<body>

    <div class="complete">
        <form action="" method="post">
    <div class="search-wrapper">
        <div class="input-holder">
            
            
                {% csrf_token %}
                <input type="hidden" name="form_type" value="prompt_from_user">
                <input type="text" class="search-input" name="user_input" placeholder="Enter the topic you want to Learn" />
                <button class="search-icon" onclick="searchToggle(this, event);"type="submit"><span></span></button>
              
            
        </div>
        <span class="close" onclick="searchToggle(this, event);"></span>
    </div>
</form>
{% if response %}

    <div class="timeline">
        <!--CARD 1-->
        {% for i in title_list %}
        <div class="card">
          <div class="card-icon">
            <i class="fa fa-book fa-fw"></i>
          </div>
          <div class="card-content">

            
            
            <h3>{{i}}</h3>
            
          </div>
          
        </div>
        {% endfor %}
      </div>
      
      <div class="start-course">
        
          <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="Start Course">
            <button type="submit"class="start-course-button"name="upvote" value="Start Course">Start Course</button>
        </form>
        
      
      </div>
    
      {% endif %}
    </div>


</body>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function searchToggle(obj, evt){
    var container = $(obj).closest('.search-wrapper');
        if(!container.hasClass('active')){
            container.addClass('active');
            evt.preventDefault();
        }
        else if(container.hasClass('active') && $(obj).closest('.input-holder').length == 0){
            container.removeClass('active');
            // clear input
            container.find('.search-input').val('');
        }
}
</script>

templates/sensei_base_trial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <h1>Teach Me </h1>
  <!-- <h3>Write an instruction</h3> -->
  <form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name="form_type" value="prompt_from_user">
    <input type="text" name="user_input" id="" >
    <button type="submit">Submit</button>
  </form>
  {% if response %}
    <h1>{{prompt}}</h1>
    <div>
      {% for i in title_list %}
      <div>
        <h2>{{i}}</h2>
      </div>
      {% endfor %}
    </div>
    
  {% endif %}


  {% if response %}
        <form action="" method="post">
          {% csrf_token %}
          <input type="hidden" name="form_type" value="Start Course">
          <input type="submit" name="upvote" value="Start Course" />
      </form>
  {% endif %}

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(window).on('beforeunload', function() {
            $.ajax({
                url: '/record-page-visit/my-page/',
                async: false,
                success: function() {}
            });
        });
    </script>
</body>
</html>

templates/sensei_classroom.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'sensei_classroom.css' %}">

<body>

  <div class="container">
    <div class="blackboard">

    {% if topic_name %}

      <h3>{{topic_name}}</h3>
    {% else %}
    <h3>Click Understood to Continue</h3>
    {% endif %}



      <div class="info-scrollable">
        
         {% if context_for_doubt %}
                {{context_for_doubt}}
         

        {% endif %}
        
    {% if response %}
        {% for i in answer %}
            <p>
                {{i}}
            </p>
        {% endfor %}
        
    {% endif %}      </div>
    </div>
    <div class="buttons">
      <span>
        <button><form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="Simplify">
            <input type="submit" name="simply" value="Simplify" />
        </form></button>
        <button><form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="next">
            <input type="submit" name="upvote" value="Understood" />
        </form></button>
        
        <button><form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="Give Examples">
            <input type="submit" name="upvote" value="Give Examples" />
        </form></button>
      </span>
      <div class="doubt-section">
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="doubt">
            <input type="text" name="user_doubt" value="doubt" />
        </form>
      </div>
      <div class="solution-doubt">
      {% if solution %}
    <div class="info-scrollable">
        {{solution}}
    </div>
    {% endif %}
</div>
      
    </div>
  </div>

</body>

templates/sensei_classroom_trial.html
<form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name="form_type" value="next">
    <input type="submit" name="upvote" value="Next" />
</form>

<form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name="form_type" value="test">
    <input type="submit" name="upvote" value="test" />
</form>
    <div>
        {% if topic_name %}
        <h2>
            {{topic_name}}
        </h2>
        {% endif %}
    </div>
  <div>

    <span id="myElement"></span>

    <!-- The script itself, loaded AFTER your root element. -->
    <script src="https://unpkg.com/typeit@8.7.1/dist/index.umd.js"></script>
    <script>
      // var mylist = JSON.parse({{mylist}})
      new TypeIt("#myElement", {
        strings: {{mylist|safe}},
        speed: 30,
      }).go();
    </script>

</body>
    {% if response %}
        {% for i in answer %}
            <p>
                {{i}}
            </p>
        {% endfor %}
        
    {% endif %}
  </div>
<div>
    {% if context_for_doubt %}
        {{context_for_doubt}}
    {% endif %}
</div>
  <div>

  </div>

  <div>
    {% if solution %}
        {{solution}}
    {% endif %}
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

templates/sensei_completed.html
Congratulations on completing the Course <br>
you can download your certificate from below

templates/sensei_controls.html
{% extends 'sensei_base.html'%}

{% block sensei_controls %}
<div>
<form>
    <button type="submit" name="action" value="Understood">Understood</button>
</form>
    <button>Did not understand</button>
    <button>Give more examples</button>
  </div>
  
{%endblock%}

templates/signup.html
<h1>Sign up</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>